"""Format-only Blender → corelib OBJ exporter.

Runs INSIDE Blender's Python process (imports bpy / bmesh). The repo installer
symlinks this file into ``~/.config/blender/<version>/scripts/modules/`` so it's
auto-importable from any Blender Python script.

This module's only job is to translate Blender meshes into a Wavefront ``.obj``
that henkelmax/corelib's ``OBJEntityRenderer`` can load without crashing or
rendering see-through. It does NOT build geometry, assign UVs, generate textures,
or otherwise constrain what the model looks like — the agent does all that in
Blender, this just serializes what it built.

The four critical gotchas it handles:

1. **Face triplets** — every face vertex written as ``v_idx/vt_idx/vn_idx``.
   corelib's loader unconditionally reads ``face[N][2]`` for the normal index;
   omitting the triplet crashes the entity renderer with
   ``ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2``.
2. **UV convention agreement** — Blender, standard OBJ, and corelib all use
   the SAME V convention: v=0 at the image bottom, v=1 at the image top. So
   **no V-flip is needed** in the typical path — the UVs you set in Blender
   are exactly what corelib will sample, and the exporter passes them through
   verbatim by default. The ``v_flip`` flag stays as an escape hatch for the
   rare case of UVs authored with the opposite convention, but the default is
   False and you almost never want to change it. (Earlier versions of this
   exporter defaulted ``v_flip=True`` based on a misread of corelib's
   behavior; that bug caused in-game textures to render mirrored vertically
   even when Blender previews looked correct. Fixed 2026-05-20.)
3. **Triangulation** — corelib expects triangles. The exporter triangulates a
   bmesh copy of each object before writing (the source mesh is untouched).
4. **CCW outward winding** — corelib + Minecraft's ``ENTITY_CUTOUT_TRIANGLES``
   path back-face-culls clockwise-outward triangles, so the model renders
   see-through. Blender Cycles previews do NOT catch this (Cycles renders
   double-sided by default). After writing, the exporter sanity-checks the
   first face: its CCW-computed normal should point away from the object's
   centroid. If not, it raises — meaning your normals are flipped in Blender
   and you need to fix them (Edit Mode → A → Mesh → Normals → Recalculate
   Outside, or ``bmesh.ops.recalc_face_normals`` in Python) before re-exporting.

Material handling: corelib binds the entity texture via Java (the
``OBJEntityRenderer`` takes a ``ResourceLocation``), NOT via OBJ ``mtllib`` /
``usemtl`` lines. The exporter therefore writes no material references — just
geometry + UVs + normals. UV layer presence is required if the entity is
textured; if no UV layer exists on a mesh, a single (0,0) UV is written and
every face vertex points to it (the model will render in a single texture
pixel — useful for solid-color debug meshes, not real entities).

Typical usage from inside a ``mcp__blender__execute_blender_code`` call::

    import bpy, bmesh
    from corelib_obj_export import export_corelib_obj

    # ... build your mesh with bmesh, place objects, assign UVs ...

    # Export all mesh objects in the scene:
    export_corelib_obj(path='/path/to/mymob.obj')

    # Or export only specific objects:
    export_corelib_obj(
        objects=[bpy.data.objects['head'], bpy.data.objects['body']],
        path='/path/to/mymob.obj',
    )
"""

import bpy
import bmesh


def export_corelib_obj(path, objects=None, verify=True, v_flip=False):
    """Export Blender mesh objects to a corelib-compatible Wavefront OBJ.

    Args:
        path: Output file path (absolute or relative to Blender's CWD).
        objects: Iterable of ``bpy.types.Object`` with ``type='MESH'``. Defaults
            to every mesh object in the current scene.
        verify: Run a CCW-outward winding sanity check after writing and raise
            ``ValueError`` if the first face's normal points toward the object
            centroid (the see-through-in-game bug). Default True.
        v_flip: Pass-through escape hatch for UVs authored with opposite V
            convention. Default False — Blender / standard OBJ / corelib all
            agree v=0 is at the image bottom, so UVs go through verbatim.
            Almost never change this.

    Raises:
        ValueError: from the winding check if the first emitted face is wound
            clockwise outward.
    """
    if objects is None:
        objects = [o for o in bpy.context.scene.objects if o.type == 'MESH']

    depsgraph = bpy.context.evaluated_depsgraph_get()
    v_global = 1   # OBJ uses 1-based indices
    vt_global = 1
    vn_global = 1

    with open(path, 'w') as f:
        f.write("# Generated by corelib_obj_export\n")
        f.write("# corelib-compatible: face triplets (v/vt/vn), triangulated, CCW outward\n")

        for obj in objects:
            obj_eval = obj.evaluated_get(depsgraph)
            src_mesh = obj_eval.to_mesh()

            bm = bmesh.new()
            bm.from_mesh(src_mesh)
            bm.transform(obj.matrix_world)   # bake world transform into vertex coords
            bmesh.ops.triangulate(bm, faces=bm.faces[:])
            bm.verts.index_update()
            bm.faces.index_update()

            uv_layer = bm.loops.layers.uv.active
            n_verts = len(bm.verts)
            n_faces = len(bm.faces)

            f.write(f"o {obj.name}\n")

            for v in bm.verts:
                co = v.co
                f.write(f"v {co.x:.6f} {co.y:.6f} {co.z:.6f}\n")

            # UVs: one per face-loop. If the mesh has no UV layer, write a single
            # (0, 0) and have every face vertex point to it.
            n_uvs_written = 0
            loop_uv_local = {}   # (face.index, corner) -> local vt offset
            if uv_layer is not None:
                for face in bm.faces:
                    for corner, loop in enumerate(face.loops):
                        u, vv = loop[uv_layer].uv
                        if v_flip:
                            vv = 1.0 - vv
                        f.write(f"vt {u:.6f} {vv:.6f}\n")
                        loop_uv_local[(face.index, corner)] = n_uvs_written
                        n_uvs_written += 1
            else:
                f.write("vt 0.0 0.0\n")
                n_uvs_written = 1

            # One normal per face (flat shading). Mob rendering through
            # OBJEntityRenderer doesn't smooth-shade across face boundaries
            # anyway, so per-vertex normals would just bloat the file.
            for face in bm.faces:
                n = face.normal
                f.write(f"vn {n.x:.6f} {n.y:.6f} {n.z:.6f}\n")

            # Face lines — emit pos/uv/normal triplets in the global OBJ index space.
            for face in bm.faces:
                vn_idx = vn_global + face.index
                triplets = []
                for corner, loop in enumerate(face.loops):
                    v_idx = v_global + loop.vert.index
                    if uv_layer is not None:
                        vt_idx = vt_global + loop_uv_local[(face.index, corner)]
                    else:
                        vt_idx = vt_global   # the lone (0, 0) UV
                    triplets.append(f"{v_idx}/{vt_idx}/{vn_idx}")
                f.write(f"f {' '.join(triplets)}\n")

            v_global += n_verts
            vt_global += n_uvs_written
            vn_global += n_faces

            bm.free()
            obj_eval.to_mesh_clear()

    if verify:
        _verify_winding(path)


def _verify_winding(path):
    """Sanity-check the first emitted face: its CCW-computed normal must point
    away from the object centroid (using all vertices of the first object as
    a centroid proxy). If it points *toward* the centroid, the face is wound
    CW outward and the model will look see-through in-game.

    Works as a tripwire for convex-ish primitives. Not a full per-face audit,
    but catches the common failure mode of an entire mesh having flipped normals.
    """
    verts = []
    first_face = None
    with open(path) as f:
        for line in f:
            if line.startswith('v '):
                p = line.split()
                verts.append((float(p[1]), float(p[2]), float(p[3])))
            elif line.startswith('f ') and first_face is None:
                first_face = line.strip()
                break
    if first_face is None or len(verts) < 3:
        return

    toks = first_face.split()[1:4]
    idx = [int(t.split('/')[0]) - 1 for t in toks]
    V0, V1, V2 = verts[idx[0]], verts[idx[1]], verts[idx[2]]
    e1 = (V1[0] - V0[0], V1[1] - V0[1], V1[2] - V0[2])
    e2 = (V2[0] - V0[0], V2[1] - V0[1], V2[2] - V0[2])
    nx = e1[1] * e2[2] - e1[2] * e2[1]
    ny = e1[2] * e2[0] - e1[0] * e2[2]
    nz = e1[0] * e2[1] - e1[1] * e2[0]

    fx = (V0[0] + V1[0] + V2[0]) / 3.0
    fy = (V0[1] + V1[1] + V2[1]) / 3.0
    fz = (V0[2] + V1[2] + V2[2]) / 3.0
    n = len(verts)
    cx = sum(v[0] for v in verts) / n
    cy = sum(v[1] for v in verts) / n
    cz = sum(v[2] for v in verts) / n
    dot = nx * (fx - cx) + ny * (fy - cy) + nz * (fz - cz)
    if dot < 0:
        raise ValueError(
            f"OBJ winding check FAILED on first face of {path!r}. "
            f"face_normal · outward = {dot:.4f} (expected > 0 for CCW outward). "
            "Normals are flipped — model will look see-through in-game. "
            "Recalculate normals in Blender before re-exporting: "
            "bmesh.ops.recalc_face_normals(bm, faces=bm.faces[:])."
        )
